packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  "@swc/core": true
  "@tarojs/binding": true
  "@tarojs/cli": true
  core-js: true
  core-js-pure: true
  esbuild: true
  prisma: true
  weapp-tailwindcss: false
minimumReleaseAgeExclude:
  - '@playwright/test@1.64.0'
  - playwright-core@1.64.0
  - playwright@1.64.0
  - vite@8.3.4
